name: dio_cache_interceptor_sembast_storage
description: A DB cache store implementation with Sembast for dio_cache_interceptor package.
version: 0.2.0
homepage: https://github.com/llfbandit/dio_cache_interceptor/tree/master/dio_cache_interceptor_sembast_storage

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  dio_cache_interceptor:
    git:
        url: git@github.com:norwegian-cruise-line/digi_fork_dio_cache_interceptor.git
        path: dio_cache_interceptor/
        ref: 3.4.4
  # https://pub.dev/packages/sembast
  sembast: ^3.4.3
  # https://pub.dev/packages/sembast_web
  sembast_web: ^2.1.2
  # https://pub.dev/packages/flat_buffers
  flat_buffers: ^2.0.5

dev_dependencies:
  # https://pub.dev/packages/build_runner
  build_runner: ^2.3.3
  # https://pub.dev/packages/lints
  lints: ^3.0.0
  # https://pub.dev/packages/test
  test: ^1.23.1